# Generated by Django 6.0.5 on 2026-05-26 23:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='AGUARDANDO_PAGAMENTO', max_length=30)),
                ('canal', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id_unidade', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=20)),
                ('estoque', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha_hash', models.CharField(max_length=255)),
                ('perfil', models.CharField(choices=[('CLIENTE', 'Cliente'), ('ATENDENTE', 'Atendente'), ('GERENTE', 'Gerente'), ('ADMIN', 'Admin')], default='CLIENTE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id_pagamento', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='PENDENTE', max_length=20)),
                ('id_pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='pedidos.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('acao', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario_responsavel', models.CharField(max_length=100)),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='pedidos.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedidos.pedido')),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id_promocao', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=200)),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('validade', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocoes', to='pedidos.produto')),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='id_unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='pedidos.unidade'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='pedidos.usuario'),
        ),
        migrations.CreateModel(
            name='Fidelizacao',
            fields=[
                ('id_fidelizacao', models.AutoField(primary_key=True, serialize=False)),
                ('saldo_ponto', models.IntegerField(default=0)),
                ('historico', models.TextField(blank=True)),
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fidelizacao', to='pedidos.usuario')),
            ],
        ),
    ]
