# Generated by Django 6.0.5 on 2026-05-27 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fidelizacao',
            old_name='id_usuario',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='itempedido',
            old_name='id_pedido',
            new_name='pedido',
        ),
        migrations.RenameField(
            model_name='itempedido',
            old_name='id_produto',
            new_name='produto',
        ),
        migrations.RenameField(
            model_name='logauditoria',
            old_name='id_pedido',
            new_name='pedido',
        ),
        migrations.RenameField(
            model_name='pagamento',
            old_name='id_pedido',
            new_name='pedido',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='id_usuario',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='id_unidade',
            new_name='unidade',
        ),
        migrations.RenameField(
            model_name='promocao',
            old_name='id_produto',
            new_name='produto',
        ),
    ]
