# Generated by Django 6.0.5 on 2026-05-27 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_rename_id_usuario_fidelizacao_usuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='canal',
            new_name='canalPedido',
        ),
    ]
